Atom a[] = {
    jbwm_ewmh[JBWM_EWMH_WM_ACTION_MOVE],
    jbwm_ewmh[JBWM_EWMH_WM_ACTION_RESIZE],
    jbwm_ewmh[JBWM_EWMH_WM_ACTION_CLOSE],
    jbwm_ewmh[JBWM_EWMH_WM_ACTION_SHADE],
    jbwm_ewmh[JBWM_EWMH_WM_ACTION_FULLSCREEN],
    jbwm_ewmh[JBWM_EWMH_WM_ACTION_CHANGE_DESKTOP],
    jbwm_ewmh[JBWM_EWMH_WM_ACTION_ABOVE],
    jbwm_ewmh[JBWM_EWMH_WM_ACTION_BELOW],
    jbwm_ewmh[JBWM_EWMH_WM_ACTION_MAXIMIZE_HORZ],
    jbwm_ewmh[JBWM_EWMH_WM_ACTION_MAXIMIZE_VERT],
};
