.TH jbwm 1 "14 SEP 2016"

.SH NAME
jbwm \- minimalistic window manager for X

.SH SYNOPSIS
.B jbwm
[\fB-1\fR \fIMODS\fR]
[\fB-2\fR \fIMODS\fR]
[\fB-b\fR \fIBG\fR]
[\fB-d\fR \fIDISPLAY\fR]
[\fB-F\fR \fIFONT\fR]
[\fB-f\fR \fIFG\fR]
[\fB-s\fR \fIFC\fR]
[\fB-V\fR]
[\fB-v\fR]

.SH DESCRIPTION
.B jbwm
is a minimalist window manager forked from evilwm, adding basic title bar
support, simpler key bindings, and various code cleanups and size
reductions.  evilwm is based on aewm, extended to feature
many keyboard controls, and otherwise altered to be more friendly.

.SH OPTIONS
Available if \fBUSE_ARGV\fR specified in build.
.IP "\fB-1 \fIMOD"
Set first modifier key.  \fBMOD\fR may be control, alt, mod1, mod2, mod3,
mod4, or mod5.
.IP "\fB-2 \fIMOD"
Set second modifier key.  \fBMOD\fR is as above.
.IP "\fB-b \fIBG"
Set background color.
.IP "\fB-d \fIDISPLAY"
Set DISPLAY.
.IP "\fB-F \fIFONT"
Set font.
.IP "\fB-f \fIFG"
Set foreground color.
.IP "\fB-s \fIFC"
Set sticky window color.
.IP "\fB-V"
.IP "\fB-v"
Print version then exit.
.IP "\fB-*"
For all other options, display usage then exit.

.SH NOTES
In jbwm, the focus follows the mouse pointer, and focus is not lost if
you stray onto the root window. 
.PP
You can use the mouse to manipulate windows either by click/dragging
the 1 pixel border, or by holding down \fBMod1\fR and doing so anywhere 
in the client window. The controls are:
.IP "\fBButton 1"
Move or raise window.
.IP "\fBButton 2"
Lower window.
.IP "\fBButton 3"
Resize window.
.PP
Most keyboard controls are used by holding down \fBMod1\fR, then
pressing a key. Available functions are:
.IP \fBEscape
Exit jbwm.
.IP \fBReturn
Spawn new terminal.
.IP \fBq
Delete current window.
.IP "\fBDown Arrow"
Lower current window.
.IP "\fBUp Arrow"
Raise current window.
.IP "\fBH, J, K, L"
Move window left, down, up or right.  Holding \fBShift\fR resizes the
window instead.
.IP \fBa
Toggle fullscreen.  
.IP \fBSpace
Toggle maximization.
.IP \fBz
Toggle vertical maximization.  
.IP \fBx
Toggle horizontal maximization.  
.IP \fBs
Toggle window shade.
.PP
If compiled with virtual desktop support, these functions are also available: 
.IP \fB.
Toggle window stickiness.
.IP "\fB1--0"
Switch virtual desktop.
.IP \fBLeft
Previous virtual desktop.
.IP \fBRight
Next virtual desktop.
.PP
In addition to the above, \fBMod1+Tab\fR can be used 
to cycle through windows on screen.

.SH ENVIRONMENT
.IP \fBDISPLAY
DISPLAY should be set, otherwise default of :0 will be used.  
.IP \fBJBWM_FC
Set sticky window border color.
.IP \fBJBWM_FG
Set foreground color.
.IP \fBJBWM_BG
Set background color.
.IP \fBJBWM_CLOSE
Set close button color.
.IP \fBJBWM_SHADE
Set shade button color.
.IP \fBJBWM_RESIZE
Set resize button color.
.IP \fBJBWM_FONT
Set font.
.IP \fBJBWM_TERM
Set terminal emulator program.

.SH BUGS
EWMH support is a work in progress.  

.SH AUTHOR
Jeffrey Bedard <\fIjefbed@gmail.com\fR>
Ciaran Anscomb <\fIevilwm@6809.org.uk\fR> wrote evilwm.
Decklin Foster <\fIfosterd@hartwick.edu\fR> wrote aewm.
David Hogan <\fIdhog@cs.su.oz.au\fR> wrote 9wm.

.SH "SEE ALSO"
.BR xinit (1),
.BR X (7)
