.TH jbwm 1 "November 29, 2016" "" ""

.SH NAME
jbwm \- Minimalist Window Manager

.SH SYNOPSIS
.B jbwm
.LP
If you have enabled ARGV support in the Makefile:
.LP
.B jbwm [ \-d
.I display
.B ] [ \-1
.I keymask for primary modifier (Default: Windows/Meta key)
.B ] [ \-2
.I keymask for secondary modifier (Default: Shift key)
.B ] [ \-V ]

.SH DESCRIPTION
.B jbwm
is a minimalist window manager forked from evilwm, adding basic titlebar
support, simpler key bindings, and various code cleanups and size
reductions.  evilwm is based on aewm, extended to feature
many keyboard controls, and otherwise altered to be more friendly.
.PP
In
.BR jbwm ,
the focus follows the mouse pointer, and focus is not lost if
you stray onto the root window. 
.PP
You can use the mouse to manipulate windows either by click/dragging
the 1 pixel border, or by holding down Windows/Meta and doing so anywhere 
in the client window. The controls are:
.IP "Button 1"
Move or raise window.
.IP "Button 2"
Lower window.
.IP "Button 3"
Resize window.
.PP
Most keyboard controls are used by holding down Windows/Meta, then
pressing a key. Available functions are:
.IP Escape
Exit jbwm.
.IP Return
Spawn new terminal.
.IP q
Delete current window.
.IP "Down Arrow"
Lower current window.
.IP "Up Arrow"
Lower current window.
.IP "H, J, K, L"
Move window left, down, up or right.  Holding Shift resizes the
window instead.
.IP Space
Maximise current window (toggle).
.IP s
Toggle window shade.
.PP
If compiled with virtual desktop support, these functions are also available: 
.IP f
Toggle window stickiness.
.IP "1--0"
Switch virtual desktop.
.IP Left
Previous virtual desktop.
.IP Right
Next virtual desktop.
.PP
In addition to the above, Windows/Meta+Tab can be used 
to cycle through windows on screen.

.SH OPTIONS
Command line arguments are accepted if jbwm was compiled with ARGV enabled
in its Makefile.  
Valid modifier values for the 
.B \-1 
and 
.B \-2 
options are 
control, alt, mod1, mod2, mod3, mod4, mod5.
.B \-V
displays the jbwm version number.  

.SH ENVIRONMENT
.IP DISPLAY
DISPLAY should be set, otherwise default of :0 will be used.  

.SH BUGS
EWMH support not fully implemented.  
More complete support of MWM hints is needed.  

.SH AUTHOR
Jeffrey Bedard <jefbed@gmail.com>
.br
evilwm was written by Ciaran Anscomb <evilwm@6809.org.uk>.
.br
aewm was written by Decklin Foster <fosterd@hartwick.edu>.
.br
9wm was written by David Hogan <dhog@cs.su.oz.au>.
.SH "SEE ALSO"
.BR xinit (1),
.BR X (7)
