; Copyright 2017, Jeffrey E. Bedard
(load "libconvert.scm")
(define convert_keys
 (lambda (in_filename out_filename)
  (letrec ((i (open-input-file in_filename))
	   (o (open-output-file out_filename))
	   (guard "JBWM_JBWMKEYS")
	   (data '())
	   (parse
	    (lambda (i o)
	     (and-let* ((line (read-line i))
			((not (eof-object? line)))
			((> (string-length line) 1)))
	      (let ((key (string-car line))
		    (value (string-cdr line)))
	       (set! data (cons (cons key value) data))
	       (parse i o)))))
	   (format-cell
	    (lambda (datum out_port)
		(display (string-append "\tJBWM_KEY_" (car datum)
		 " = XK_" (cdr datum) ",\n") out_port))))
	(begin-include guard o)
	(display-c-include "<X11/keysym.h>" o)
	(display "enum JBWMKeys {\n" o)
	(parse i o)
	(display data)
	(map (lambda (n) (format-cell n o)) data)
	(display "};\n" o)
	(display-c-include "\"key_combos.h\"" o)
	(end-include guard o)
	(close-port i)
	(close-port o))))
(convert_keys "keys.txt" "JBWMKeys.h")
