(define copyright "// Copyright 2017, Jeffrey E. Bedard\n")
; The following prefix is applied to each entry
(define master-prefix "_NET_")
(define begin-array-definition (lambda (name)
	(display (string-append copyright
		"static char * " name " [] = {\n"))))
(define begin-enum-definition (lambda (name)
	(display (string-append "enum " name " {\n"))))
(define end-c-definition (lambda () (display "};\n")))
(define get-array-line (lambda (prefix item)
	(string-append "\t\"" master-prefix prefix item "\",\n")))
(define print-each-array-element (lambda (prefix l)
	(map (lambda (item) (display (get-array-line prefix item))) l)))
(define get-enum-line (lambda (prefix item)
	(string-append "\t" master-prefix prefix item ",\n")))
(define print-enum-line (lambda (prefix item)
	(display (get-enum-line prefix item))))
(define print-each-enum (lambda (prefix l)
	(map (lambda (item) (print-enum-line prefix item)) l)))
(define get-guard (lambda (name) 
	(string-append "JBWM_" name "_H\n")))
(define print-each (lambda (function data)
	(function (car data) (cdr data))))
(define write-include-header (lambda (ig)
	(display (string-append copyright
		"#ifndef " (get-guard ig)
		"#define " (get-guard ig)))))
(define write-include-fin (lambda (ig) (display (string-append "#endif//!"
	(get-guard ig)))))
