jbwm_cflags=-Os
# Compile for current machine
jbwm_cflags+=-march=native
# Tuning
jbwm_cflags+=-fomit-frame-pointer -pipe -flto
#jbwm_cflags+=-W -Wall -Wextra
# disable everything for minimal configuration 
#jbwm_cflags+=-DNDEBUG
CFLAGS=${jbwm_cflags}
include jbwm.mk
