# jbwm - Minimalist Window Manager for X
# Copyright 2008-2016, Jeffrey E. Bedard <jefbed@gmail.com> 
# Copyright 1999-2015, Ciaran Anscomb <jbwm@6809.org.uk>
# See README for license and other details.
jbwm_cflags+=-Wall -Wextra
# Titlebar Xft support:
include xft.mk
# Uncomment to enable title bars
include title_bar.mk
include jbwm.mk
