CFLAGS=-Os
# Compile for current machine
CFLAGS+=-march=native
# Tuning
CFLAGS+=-fomit-frame-pointer -pipe -flto
CFLAGS+=-W -Wall -Wextra

# Uncomment to disable everything for minimal configuration 
CFLAGS=-Os
DEFINES=-DNDEBUG
EXTRASRCS=
EXTRALIBS=
EXTRAINCLUDES=

include jbwm.mk
