CFLAGS=-Os
# Compile for current machine
#CFLAGS+=-march=native
# Tuning
CFLAGS+=-fomit-frame-pointer -pipe -flto
CFLAGS+=-W -Wall -Wextra
# disable everything for minimal configuration 
CFLAGS=-DNDEBUG
include jbwm.mk
