# Debug
CFLAGS=-O0
CFLAGS+=-ggdb
CFLAGS+=-DDEBUG
CFLAGS+=-DXDEBUG
# Profile
CFLAGS+=-pg
# Enable all warnings
CFLAGS+=-W -Wall -Wextra -Werror

DEFINES += -DUSE_ARGV 
DEFINES += -DSTDIO

include ewmh.mk
include mwm.mk
include shape.mk
include snap.mk
include titlebar.mk
include xft.mk


include jbwm.mk
