# Debug
CFLAGS=-O0
CFLAGS+=-ggdb
CFLAGS+=-DDEBUG
CFLAGS+=-DXDEBUG
# Profile
CFLAGS+=-pg
# Enable all warnings
CFLAGS+=-W -Wall -Wextra -Werror

# Uncomment to enable SHAPE extension support
DEFINES += -DUSE_SHAPE
EXTRALIBS += -lXext # Required for SHAPE extension
include xft.mk
DEFINES += -DUSE_ARGV 
DEFINES += -DUSE_TBAR
EXTRASRCS += titlebar.c 
include snap.mk
DEFINES += -DSTDIO
include ewmh.mk
DEFINES += -DGRAVITY

# Uncomment to enable MWM hints
include mwm.mk

include jbwm.mk
