#!/bin/sh

STASHDIR=/usr/local/stash
PREFIX=/usr/local

#STASHDIR=$HOME/tmp/stash
#PREFIX=$HOME/tmp

if [ "$1" = "" ]; then
	ls $STASHDIR
	exit
fi

if [ "$1" = "-a" ]; then
	for DIR in $STASHDIR; do
		stash $DIR
	done
	exit
fi

get_items()
{
	find . | cut -d. -f2- | cut -d/ -f2-
}

if [ "$1" = "-r" ]; then
	cd $STASHDIR/$2
	CONTENTS=`mktemp`
	get_items > $CONTENTS
	cd $PREFIX
	xargs -a $CONTENTS rm -f 2> /dev/null
	cat $CONTENTS
	rm $CONTENTS
	exit
fi
stash -r $1
cd $STASHDIR/$1
for I in `get_items`; do
	if [ -d "$I" ]; then
		mkdir -p $PREFIX/$I
	else
		ln -s $STASHDIR/$1/$I $PREFIX/$I
	fi
done
#cp -l -r -f * $PREFIX
#cp -l -r -n * $PREFIX

