.TH "_ARWMTitlebarData" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ARWMTitlebarData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <titlebar.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "Bool \fBinitialized\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBARWMButton\fP * \fBclose\fP"
.br
.ti -1c
.RI "   \fBARWMButton\fP * \fBresize\fP"
.br
.ti -1c
.RI "   \fBARWMButton\fP * \fBshade\fP"
.br
.ti -1c
.RI "   \fBARWMButton\fP * \fBhandle\fP"
.br
.ti -1c
.RI "} \fBbuttons\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file titlebar.h.
.SH "Field Documentation"
.PP 
.SS "struct { ... }   \fBbuttons\fP"
.SS "\fBARWMButton\fP* \fBclose\fP"
.PP
Definition at line 12 of file titlebar.h.
.SS "\fBARWMButton\fP * \fBhandle\fP"
.PP
Definition at line 12 of file titlebar.h.
.SS "Bool \fBinitialized\fP"
.PP
Definition at line 8 of file titlebar.h.
.SS "\fBARWMButton\fP * \fBresize\fP"
.PP
Definition at line 12 of file titlebar.h.
.SS "\fBARWMButton\fP * \fBshade\fP"
.PP
Definition at line 12 of file titlebar.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
