.TH "_ARWMButton" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ARWMButton \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ARWMButton.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "Window \fBparent\fP"
.br
.ti -1c
.RI "XColor \fBcolor\fP"
.br
.ti -1c
.RI "GC \fBgc\fP"
.br
.ti -1c
.RI "XRectangle \fBgeometry\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file ARWMButton.h.
.SH "Field Documentation"
.PP 
.SS "XColor \fBcolor\fP"
.PP
Definition at line 7 of file ARWMButton.h.
.SS "GC \fBgc\fP"
.PP
Definition at line 8 of file ARWMButton.h.
.SS "XRectangle \fBgeometry\fP"
.PP
Definition at line 9 of file ARWMButton.h.
.SS "Window \fBparent\fP"
.PP
Definition at line 6 of file ARWMButton.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
