.TH "/home/jefbed/src/arwm/application_t.h" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/application_t.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBApplication\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBApplication\fP \fBApplication\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBApplication\fP \fBApplication\fP"
.PP
Definition at line 4 of file application_t.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
