.TH "Application" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <application_t.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBres_name\fP"
.br
.ti -1c
.RI "char * \fBres_class\fP"
.br
.ti -1c
.RI "\fBubyte\fP \fBgeometry_mask\fP"
.br
.ti -1c
.RI "XRectangle \fBgeometry\fP"
.br
.ti -1c
.RI "\fBApplication\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file application_t.h.
.SH "Field Documentation"
.PP 
.SS "XRectangle \fBgeometry\fP"
.PP
Definition at line 10 of file application_t.h.
.SS "\fBubyte\fP \fBgeometry_mask\fP"
.PP
Definition at line 9 of file application_t.h.
.SS "\fBApplication\fP* \fBnext\fP"
.PP
Definition at line 11 of file application_t.h.
.SS "char* \fBres_class\fP"
.PP
Definition at line 8 of file application_t.h.
.SS "char* \fBres_name\fP"
.PP
Definition at line 7 of file application_t.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
