.TH "/home/jefbed/src/arwm/armacros.h" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/armacros.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBARBUGPARAM\fP(message)   '%s:%d: %s', __FILE__, __LINE__, message"
.br
.ti -1c
.RI "#define \fBARBUG\fP(message)   g_debug(ARBUGPARAM(message))"
.br
.ti -1c
.RI "#define \fBARWARN\fP(message)   g_warning(ARBUGPARAM(message))"
.br
.ti -1c
.RI "#define \fBARERR\fP(message)   g_error(ARBUGPARAM(message))"
.br
.ti -1c
.RI "#define \fBARBBOOL\fP(x)   (x == TRUE)"
.br
.ti -1c
.RI "#define \fBARPBOOL\fP(x)   (x != NULL)"
.br
.ti -1c
.RI "#define \fBARASSERT\fP"
.br
.ti -1c
.RI "#define \fBARBASSERT\fP(x)"
.br
.ti -1c
.RI "#define \fBARPASSERT\fP(x)"
.br
.ti -1c
.RI "#define \fBARIFB\fP(x)   if(ARBBOOL(x))"
.br
.ti -1c
.RI "#define \fBARIFNB\fP(x)   if(!ARBBOOL(x))"
.br
.ti -1c
.RI "#define \fBARIFP\fP(x)   if(ARPBOOL(x))"
.br
.ti -1c
.RI "#define \fBARIFNP\fP(x)   if(!ARPBOOL(x))"
.br
.ti -1c
.RI "#define \fBARWIFNP\fP(x)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ARASSERT"
.PP
Definition at line 44 of file armacros.h.
.SS "#define ARBASSERT(x)"
.PP
Definition at line 54 of file armacros.h.
.SS "#define ARBBOOL(x)   (x == TRUE)"
.PP
Definition at line 38 of file armacros.h.
.SS "#define ARBUG(message)   g_debug(ARBUGPARAM(message))"
.PP
Definition at line 29 of file armacros.h.
.SS "#define ARBUGPARAM(message)   '%s:%d: %s', __FILE__, __LINE__, message"
.PP
Definition at line 26 of file armacros.h.
.SS "#define ARERR(message)   g_error(ARBUGPARAM(message))"
.PP
Definition at line 35 of file armacros.h.
.SS "#define ARIFB(x)   if(ARBBOOL(x))"
.PP
Definition at line 58 of file armacros.h.
.SS "#define ARIFNB(x)   if(!ARBBOOL(x))"
.PP
Definition at line 61 of file armacros.h.
.SS "#define ARIFNP(x)   if(!ARPBOOL(x))"
.PP
Definition at line 67 of file armacros.h.
.SS "#define ARIFP(x)   if(ARPBOOL(x))"
.PP
Definition at line 64 of file armacros.h.
.SS "#define ARPASSERT(x)"
.PP
Definition at line 55 of file armacros.h.
.SS "#define ARPBOOL(x)   (x != NULL)"
.PP
Definition at line 39 of file armacros.h.
.SS "#define ARWARN(message)   g_warning(ARBUGPARAM(message))"
.PP
Definition at line 32 of file armacros.h.
.SS "#define ARWIFNP(x)"\fBValue:\fP
.PP
.nf
ARIFNP(x) \
                ARWARN('NULL data passed, operation not performed'); \
        else
.fi
.PP
Definition at line 70 of file armacros.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
