.TH "/home/jefbed/src/arwm/ARWMButton.h" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/ARWMButton.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_ARWMButton\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_ARWMButton\fP \fBARWMButton\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBARWMButton\fP * \fBARWMButton_new\fP (Window parent, GC gc, const unsigned short width, const unsigned short height, void *image __attribute((unused)))"
.br
.ti -1c
.RI "void \fBARWMButton_delete\fP (\fBARWMButton\fP *button)"
.br
.ti -1c
.RI "void \fBARWMButton_draw\fP (\fBARWMButton\fP *button)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_ARWMButton\fP  \fBARWMButton\fP"
.SH "Function Documentation"
.PP 
.SS "void ARWMButton_delete (\fBARWMButton\fP *button)"
.PP
Definition at line 4 of file ARWMButton.c.
.SS "void ARWMButton_draw (\fBARWMButton\fP *button)"
.PP
Definition at line 11 of file ARWMButton.c.
.SS "\fBARWMButton\fP* ARWMButton_new (Windowparent, GCgc, const unsigned shortwidth, const unsigned shortheight, void *image __attribute(unused))"
.PP
Definition at line 64 of file ARWMButton.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
