.TH "/home/jefbed/src/arwm/arwm.c" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/arwm.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <signal.h>\fP
.br
\fC#include <X11/cursorfont.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include 'arwm.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBFONTOPEN\fP(f)   XLoadQueryFont(arwm.X.dpy, f)"
.br
.ti -1c
.RI "#define \fBGRAB\fP(mod)"
.br
.ti -1c
.RI "#define \fBCOLORALLOC\fP(item)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBarwm_grab_button\fP (Window w, unsigned int mask, unsigned int button)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc __attribute__((unused)), char **argv __attribute__((unused)))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBARWMEnvironment\fP \fBarwm\fP"
.br
.ti -1c
.RI "\fBGlobalOptions\fP \fBopt\fP"
.br
.ti -1c
.RI "\fBApplication\fP * \fBhead_app\fP = NULL"
.br
.ti -1c
.RI "\fBClient\fP * \fBhead_client\fP = NULL"
.br
.ti -1c
.RI "\fBClient\fP * \fBcurrent\fP = NULL"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define COLORALLOC(item)"\fBValue:\fP
.PP
.nf
XAllocNamedColor(arwm.X.dpy, DefaultColormap(arwm.X.dpy, i),\
                opt.color.item, &arwm.X.screens[i].item, &dummy);
.fi
.SS "#define FONTOPEN(f)   XLoadQueryFont(arwm.X.dpy, f)"
.SS "#define GRAB(mod)"\fBValue:\fP
.PP
.nf
XGrabButton(arwm.X.dpy, button, mask | mod, w, False,\
        ButtonMask, GrabModeAsync, GrabModeSync, None, None)
.fi
.SH "Function Documentation"
.PP 
.SS "void arwm_grab_button (Windoww, unsigned intmask, unsigned intbutton)"
.PP
Definition at line 205 of file arwm.c.
.SS "int main (int argc __attribute__(unused), char **argv __attribute__(unused))"
.PP
Definition at line 366 of file arwm.c.
.SH "Variable Documentation"
.PP 
.SS "\fBARWMEnvironment\fP \fBarwm\fP"
.PP
Definition at line 14 of file arwm.c.
.SS "\fBClient\fP* \fBcurrent\fP = NULL"
.PP
Definition at line 47 of file arwm.c.
.SS "\fBApplication\fP* \fBhead_app\fP = NULL"
.PP
Definition at line 43 of file arwm.c.
.SS "\fBClient\fP* \fBhead_client\fP = NULL"
.PP
Definition at line 46 of file arwm.c.
.SS "\fBGlobalOptions\fP \fBopt\fP"\fBInitial value:\fP
.PP
.nf
 
{
        DEF_FONT,
        {DEF_FG, DEF_BG, DEF_FC},
        DEF_TERM
}
.fi
.PP
Definition at line 36 of file arwm.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
