.TH "/home/jefbed/src/arwm/arwmenv.h" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/arwmenv.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'titlebar.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBARWMEnvironment\fP"
.br
.ti -1c
.RI "struct \fBGlobalOptions\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBARWM_FLAG_NEED_TIDY\fP   1"
.br
.ti -1c
.RI "#define \fBARWM_FLAG_HAVE_SHAPE\fP   1 << 1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBARWMEnvironment\fP \fBARWMEnvironment\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBGlobalOptions\fP \fBopt\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ARWM_FLAG_HAVE_SHAPE   1 << 1"
.PP
Definition at line 43 of file arwmenv.h.
.SS "#define ARWM_FLAG_NEED_TIDY   1"
.PP
Definition at line 42 of file arwmenv.h.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBARWMEnvironment\fP \fBARWMEnvironment\fP"
.PP
Definition at line 47 of file arwmenv.h.
.SH "Variable Documentation"
.PP 
.SS "\fBGlobalOptions\fP \fBopt\fP"
.PP
Definition at line 36 of file arwm.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
