.TH "/home/jefbed/src/arwm/arwmmod.h" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/arwmmod.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'config.h'\fP
.br
\fC#include 'keymap.h'\fP
.br
\fC#include 'ewmh.h'\fP
.br
\fC#include 'screen.h'\fP
.br
\fC#include 'client.h'\fP
.br
\fC#include 'titlebar.h'\fP
.br
\fC#include 'new.h'\fP
.br
\fC#include 'events.h'\fP
.br
\fC#include 'graphics.h'\fP
.br
\fC#include 'key_event.h'\fP
.br
\fC#include 'button_event.h'\fP
.br
\fC#include 'configure_event.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
