.TH "ARWMEnvironment" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARWMEnvironment \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arwmenv.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile Window \fBinitialising\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   unsigned int \fBnumlock\fP"
.br
.ti -1c
.RI "   unsigned int \fBgrab\fP"
.br
.ti -1c
.RI "   unsigned int \fBmod\fP"
.br
.ti -1c
.RI "} \fBkeymasks\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   Display * \fBdpy\fP"
.br
.ti -1c
.RI "   XFontStruct * \fBfont\fP"
.br
.ti -1c
.RI "   \fBubyte\fP \fBnum_screens\fP"
.br
.ti -1c
.RI "   \fBScreenInfo\fP * \fBscreens\fP"
.br
.ti -1c
.RI "   Cursor \fBcursor\fP"
.br
.ti -1c
.RI "} \fBX\fP"
.br
.ti -1c
.RI "\fBARWMTitlebarData\fP \fBtitlebar\fP"
.br
.ti -1c
.RI "\fBubyte\fP \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file arwmenv.h.
.SH "Field Documentation"
.PP 
.SS "Cursor \fBcursor\fP"
.PP
Definition at line 36 of file arwmenv.h.
.SS "Display* \fBdpy\fP"
.PP
Definition at line 28 of file arwmenv.h.
.SS "\fBubyte\fP \fBflags\fP"
.PP
Definition at line 44 of file arwmenv.h.
.SS "XFontStruct* \fBfont\fP"
.PP
Definition at line 32 of file arwmenv.h.
.SS "unsigned int \fBgrab\fP"
.PP
Definition at line 23 of file arwmenv.h.
.SS "volatile Window \fBinitialising\fP"
.PP
Definition at line 17 of file arwmenv.h.
.SS "struct { ... }   \fBkeymasks\fP"
.SS "unsigned int \fBmod\fP"
.PP
Definition at line 23 of file arwmenv.h.
.SS "\fBubyte\fP \fBnum_screens\fP"
.PP
Definition at line 34 of file arwmenv.h.
.SS "unsigned int \fBnumlock\fP"
.PP
Definition at line 23 of file arwmenv.h.
.SS "\fBScreenInfo\fP* \fBscreens\fP"
.PP
Definition at line 35 of file arwmenv.h.
.SS "\fBARWMTitlebarData\fP \fBtitlebar\fP"
.PP
Definition at line 41 of file arwmenv.h.
.SS "struct { ... }   \fBX\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
