.TH "/home/jefbed/src/arwm/atoms.h" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/atoms.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBGETATOM\fP(atom)   XInternAtom(arwm.X.dpy, atom, False)"
.br
.ti -1c
.RI "#define \fBARWM_ATOM_VWM_STATE\fP   GETATOM('_NET_WM_STATE')"
.br
.ti -1c
.RI "#define \fBARWM_ATOM_VWM_DESKTOP\fP   GETATOM('_NET_WM_DESKTOP')"
.br
.ti -1c
.RI "#define \fBARWM_ATOM_VWM_STICKY\fP   GETATOM('_NET_WM_STATE_STICKY')"
.br
.ti -1c
.RI "#define \fBARWM_ATOM_WM_STATE\fP   GETATOM('WM_STATE')"
.br
.ti -1c
.RI "#define \fBARWM_ATOM_WM_PROTOS\fP   GETATOM('WM_PROTOCOLS')"
.br
.ti -1c
.RI "#define \fBARWM_ATOM_WM_DELETE\fP   GETATOM('WM_DELETE_WINDOW')"
.br
.ti -1c
.RI "#define \fBARWM_ATOM_MWM_HINTS\fP   GETATOM('_XA_MWM_HINTS');"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ARWM_ATOM_MWM_HINTS   GETATOM('_XA_MWM_HINTS');"
.PP
Definition at line 14 of file atoms.h.
.SS "#define ARWM_ATOM_VWM_DESKTOP   GETATOM('_NET_WM_DESKTOP')"
.PP
Definition at line 7 of file atoms.h.
.SS "#define ARWM_ATOM_VWM_STATE   GETATOM('_NET_WM_STATE')"
.PP
Definition at line 6 of file atoms.h.
.SS "#define ARWM_ATOM_VWM_STICKY   GETATOM('_NET_WM_STATE_STICKY')"
.PP
Definition at line 8 of file atoms.h.
.SS "#define ARWM_ATOM_WM_DELETE   GETATOM('WM_DELETE_WINDOW')"
.PP
Definition at line 12 of file atoms.h.
.SS "#define ARWM_ATOM_WM_PROTOS   GETATOM('WM_PROTOCOLS')"
.PP
Definition at line 11 of file atoms.h.
.SS "#define ARWM_ATOM_WM_STATE   GETATOM('WM_STATE')"
.PP
Definition at line 10 of file atoms.h.
.SS "#define GETATOM(atom)   XInternAtom(arwm.X.dpy, atom, False)"
.PP
Definition at line 4 of file atoms.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
