.TH "/home/jefbed/src/arwm/button_event.h" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/button_event.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBarwm_handle_button_event\fP (XButtonEvent *e)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void arwm_handle_button_event (XButtonEvent *e)"
.PP
Definition at line 65 of file button_event.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
