.TH "Client" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Client \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <client_t.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "Window \fBwindow\fP"
.br
.ti -1c
.RI "Window \fBparent\fP"
.br
.ti -1c
.RI "\fBScreenInfo\fP * \fBscreen\fP"
.br
.ti -1c
.RI "int \fBignore_unmap\fP"
.br
.ti -1c
.RI "XRectangle \fBgeometry\fP"
.br
.ti -1c
.RI "\fBubyte\fP \fBborder\fP"
.br
.ti -1c
.RI "XRectangle \fBold_geometry\fP"
.br
.ti -1c
.RI "unsigned int \fBexposed_width\fP"
.br
.ti -1c
.RI "unsigned int \fBmin_width\fP"
.br
.ti -1c
.RI "unsigned int \fBmin_height\fP"
.br
.ti -1c
.RI "unsigned int \fBmax_width\fP"
.br
.ti -1c
.RI "unsigned int \fBmax_height\fP"
.br
.ti -1c
.RI "int \fBwidth_inc\fP"
.br
.ti -1c
.RI "int \fBheight_inc\fP"
.br
.ti -1c
.RI "int \fBbase_width\fP"
.br
.ti -1c
.RI "int \fBbase_height\fP"
.br
.ti -1c
.RI "\fBubyte\fP \fBold_border\fP"
.br
.ti -1c
.RI "\fBbyte\fP \fBvdesk\fP"
.br
.ti -1c
.RI "int \fBshade_height\fP"
.br
.ti -1c
.RI "Atom \fBwindow_type\fP"
.br
.ti -1c
.RI "unsigned short int \fBflags\fP"
.br
.ti -1c
.RI "XConfigureEvent \fBce\fP"
.br
.ti -1c
.RI "\fBClient\fP * \fBnext\fP"
.br
.ti -1c
.RI "Window \fBclose_button\fP"
.br
.ti -1c
.RI "Window \fBresize_handle_right\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file client_t.h.
.SH "Field Documentation"
.PP 
.SS "int \fBbase_height\fP"
.PP
Definition at line 27 of file client_t.h.
.SS "int \fBbase_width\fP"
.PP
Definition at line 27 of file client_t.h.
.SS "\fBubyte\fP \fBborder\fP"
.PP
Definition at line 19 of file client_t.h.
.SS "XConfigureEvent \fBce\fP"
.PP
Definition at line 50 of file client_t.h.
.SS "Window \fBclose_button\fP"
.PP
Definition at line 56 of file client_t.h.
.SS "unsigned int \fBexposed_width\fP"
.PP
Definition at line 22 of file client_t.h.
.SS "unsigned short int \fBflags\fP"
.PP
Definition at line 44 of file client_t.h.
.SS "XRectangle \fBgeometry\fP"
.PP
Definition at line 18 of file client_t.h.
.SS "int \fBheight_inc\fP"
.PP
Definition at line 26 of file client_t.h.
.SS "int \fBignore_unmap\fP"
.PP
Definition at line 16 of file client_t.h.
.SS "unsigned int \fBmax_height\fP"
.PP
Definition at line 25 of file client_t.h.
.SS "unsigned int \fBmax_width\fP"
.PP
Definition at line 25 of file client_t.h.
.SS "unsigned int \fBmin_height\fP"
.PP
Definition at line 24 of file client_t.h.
.SS "unsigned int \fBmin_width\fP"
.PP
Definition at line 24 of file client_t.h.
.SS "\fBClient\fP* \fBnext\fP"
.PP
Definition at line 51 of file client_t.h.
.SS "\fBubyte\fP \fBold_border\fP"
.PP
Definition at line 28 of file client_t.h.
.SS "XRectangle \fBold_geometry\fP"
.PP
Definition at line 20 of file client_t.h.
.SS "Window \fBparent\fP"
.PP
Definition at line 11 of file client_t.h.
.SS "Window \fBresize_handle_right\fP"
.PP
Definition at line 57 of file client_t.h.
.SS "\fBScreenInfo\fP* \fBscreen\fP"
.PP
Definition at line 12 of file client_t.h.
.SS "int \fBshade_height\fP"
.PP
Definition at line 30 of file client_t.h.
.SS "\fBbyte\fP \fBvdesk\fP"
.PP
Definition at line 29 of file client_t.h.
.SS "int \fBwidth_inc\fP"
.PP
Definition at line 26 of file client_t.h.
.SS "Window \fBwindow\fP"
.PP
Definition at line 10 of file client_t.h.
.SS "Atom \fBwindow_type\fP"
.PP
Definition at line 32 of file client_t.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
