.TH "/home/jefbed/src/arwm/client.c" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/client.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'arwm.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBClient\fP * \fBfind_client\fP (Window w)"
.br
.ti -1c
.RI "void \fBset_wm_state\fP (\fBClient\fP *c, int state)"
.br
.ti -1c
.RI "void \fBinitialize_client_ce\fP (\fBClient\fP *c)"
.br
.ti -1c
.RI "void \fBsend_config\fP (\fBClient\fP *c)"
.br
.ti -1c
.RI "void \fBselect_client\fP (\fBClient\fP *c)"
.br
.ti -1c
.RI "void \fBfix_client\fP (\fBClient\fP *c)"
.br
.ti -1c
.RI "void \fBremove_client\fP (\fBClient\fP *c)"
.br
.ti -1c
.RI "void \fBsend_wm_delete\fP (\fBClient\fP *c, int kill_client)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBClient\fP* find_client (Windoww)"
.PP
Definition at line 14 of file client.c.
.SS "void fix_client (\fBClient\fP *c)"
.PP
Definition at line 102 of file client.c.
.SS "void initialize_client_ce (\fBClient\fP *c)"
.PP
Definition at line 50 of file client.c.
.SS "void remove_client (\fBClient\fP *c)"
.PP
Definition at line 139 of file client.c.
.SS "void select_client (\fBClient\fP *c)"
.PP
Definition at line 67 of file client.c.
.SS "void send_config (\fBClient\fP *c)"
.PP
Definition at line 60 of file client.c.
.SS "void send_wm_delete (\fBClient\fP *c, intkill_client)"
.PP
Definition at line 168 of file client.c.
.SS "void set_wm_state (\fBClient\fP *c, intstate)"
.PP
Definition at line 33 of file client.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
