.TH "/home/jefbed/src/arwm/configure_event.h" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/configure_event.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBarwm_handle_configure_request\fP (XConfigureRequestEvent *e)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void arwm_handle_configure_request (XConfigureRequestEvent *e)"
.PP
Definition at line 44 of file configure_event.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
