.TH "/home/jefbed/src/arwm/config.h" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/config.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'macros.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDEF_FONT\fP   '8x13bold'"
.br
.ti -1c
.RI "#define \fBDEF_FG\fP   '#eef'"
.br
.ti -1c
.RI "#define \fBDEF_BG\fP   '#444'"
.br
.ti -1c
.RI "#define \fBTITLEBAR_BG\fP   0x40, 0x40, 0x40"
.br
.ti -1c
.RI "#define \fBTITLEBAR_RESIZE_BG\fP   0x70, 0x70, 0xA0"
.br
.ti -1c
.RI "#define \fBTITLEBAR_CLOSE_BG\fP   0xA0, 0x70, 0x80"
.br
.ti -1c
.RI "#define \fBTITLEBAR_SHADE_BG\fP   0x70, 0xA0, 0x80"
.br
.ti -1c
.RI "#define \fBGRAB_MASK\fP   Mod1Mask"
.br
.ti -1c
.RI "#define \fBLOCK_MASK\fP   LockMask"
.br
.ti -1c
.RI "#define \fBMOD_MASK\fP   ControlMask"
.br
.ti -1c
.RI "#define \fBARWM_BORDER_WIDTH\fP   1"
.br
.ti -1c
.RI "#define \fBARWM_SNAP_DISTANCE\fP   4"
.br
.ti -1c
.RI "#define \fBDEF_FC\fP   '#ccf'"
.br
.ti -1c
.RI "#define \fBSPACE\fP   3"
.br
.ti -1c
.RI "#define \fBDEF_TERM\fP   'rxvt'"
.br
.ti -1c
.RI "#define \fBXLOCK_CMD\fP   'slock'"
.br
.ti -1c
.RI "#define \fBTITLE_FONT_HEIGHT\fP   (arwm.X.font->ascent+arwm.X.font->descent)"
.br
.ti -1c
.RI "#define \fBTITLEBAR_HEIGHT\fP   8"
.br
.ti -1c
.RI "#define \fBBUTTON_WIDTH\fP   (TITLEBAR_HEIGHT-ARWM_BORDER_WIDTH)"
.br
.ti -1c
.RI "#define \fBARWM_RESIZE_INCREMENT\fP   TITLEBAR_HEIGHT"
.br
.ti -1c
.RI "#define \fBARWM_DEFAULT_SNAP\fP   8"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ARWM_BORDER_WIDTH   1"
.PP
Definition at line 30 of file config.h.
.SS "#define ARWM_DEFAULT_SNAP   8"
.PP
Definition at line 65 of file config.h.
.SS "#define ARWM_RESIZE_INCREMENT   TITLEBAR_HEIGHT"
.PP
Definition at line 63 of file config.h.
.SS "#define ARWM_SNAP_DISTANCE   4"
.PP
Definition at line 31 of file config.h.
.SS "#define BUTTON_WIDTH   (TITLEBAR_HEIGHT-ARWM_BORDER_WIDTH)"
.PP
Definition at line 62 of file config.h.
.SS "#define DEF_BG   '#444'"
.PP
Definition at line 20 of file config.h.
.SS "#define DEF_FC   '#ccf'"
.PP
Definition at line 33 of file config.h.
.SS "#define DEF_FG   '#eef'"
.PP
Definition at line 19 of file config.h.
.SS "#define DEF_FONT   '8x13bold'"
.PP
Definition at line 15 of file config.h.
.SS "#define DEF_TERM   'rxvt'"
.PP
Definition at line 38 of file config.h.
.SS "#define GRAB_MASK   Mod1Mask"
.PP
Definition at line 26 of file config.h.
.SS "#define LOCK_MASK   LockMask"
.PP
Definition at line 27 of file config.h.
.SS "#define MOD_MASK   ControlMask"
.PP
Definition at line 28 of file config.h.
.SS "#define SPACE   3"
.PP
Definition at line 34 of file config.h.
.SS "#define TITLE_FONT_HEIGHT   (arwm.X.font->ascent+arwm.X.font->descent)"
.PP
Definition at line 53 of file config.h.
.SS "#define TITLEBAR_BG   0x40, 0x40, 0x40"
.PP
Definition at line 21 of file config.h.
.SS "#define TITLEBAR_CLOSE_BG   0xA0, 0x70, 0x80"
.PP
Definition at line 23 of file config.h.
.SS "#define TITLEBAR_HEIGHT   8"
.PP
Definition at line 59 of file config.h.
.SS "#define TITLEBAR_RESIZE_BG   0x70, 0x70, 0xA0"
.PP
Definition at line 22 of file config.h.
.SS "#define TITLEBAR_SHADE_BG   0x70, 0xA0, 0x80"
.PP
Definition at line 24 of file config.h.
.SS "#define XLOCK_CMD   'slock'"
.PP
Definition at line 40 of file config.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
