.TH "/home/jefbed/src/arwm/events.c" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/events.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib.h>\fP
.br
\fC#include 'arwm.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBarwm_current_to_head\fP (void)"
.br
.ti -1c
.RI "void \fBevent_main_loop\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void arwm_current_to_head (void)"
.PP
Definition at line 9 of file events.c.
.SS "void event_main_loop (void)"
.PP
Definition at line 259 of file events.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
