.TH "/home/jefbed/src/arwm/flags.h" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/flags.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBARWM_BOOL_NONE\fP   0"
.br
.ti -1c
.RI "#define \fBARWM_BOOL_USE_TITLEBAR\fP   1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBBooleanSet\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ARWM_BOOL_NONE   0"
.PP
Definition at line 7 of file flags.h.
.SS "#define ARWM_BOOL_USE_TITLEBAR   1"
.PP
Definition at line 8 of file flags.h.
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned char \fBBooleanSet\fP"
.PP
Definition at line 5 of file flags.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
