.TH "GlobalOptions" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GlobalOptions \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arwmenv.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBfont\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   char * \fBfg\fP"
.br
.ti -1c
.RI "   char * \fBbg\fP"
.br
.ti -1c
.RI "   char * \fBfc\fP"
.br
.ti -1c
.RI "} \fBcolor\fP"
.br
.ti -1c
.RI "char * \fBterm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file arwmenv.h.
.SH "Field Documentation"
.PP 
.SS "char* \fBbg\fP"
.PP
Definition at line 55 of file arwmenv.h.
.SS "struct { ... }   \fBcolor\fP"
.SS "char* \fBfc\fP"
.PP
Definition at line 56 of file arwmenv.h.
.SS "char* \fBfg\fP"
.PP
Definition at line 54 of file arwmenv.h.
.SS "char* \fBfont\fP"
.PP
Definition at line 51 of file arwmenv.h.
.SS "char* \fBterm\fP"
.PP
Definition at line 58 of file arwmenv.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
