.TH "/home/jefbed/src/arwm/graphics.h" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/graphics.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ARWMButton.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBarwm_new_gc\fP(r, g, b)   arwm_new_gc_for_XColor(arwm_get_XColor(r, g, b))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "GC \fBarwm_new_gc_for_XColor\fP (XColor color)"
.br
.ti -1c
.RI "XColor \fBarwm_get_XColor\fP (const \fBubyte\fP r, const \fBubyte\fP g, const \fBubyte\fP b)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define arwm_new_gc(r, g, b)   arwm_new_gc_for_XColor(arwm_get_XColor(r, g, b))"
.PP
Definition at line 15 of file graphics.h.
.SH "Function Documentation"
.PP 
.SS "XColor arwm_get_XColor (const \fBubyte\fPr, const \fBubyte\fPg, const \fBubyte\fPb)"
.PP
Definition at line 6 of file graphics.c.
.SS "GC arwm_new_gc_for_XColor (XColorcolor)"
.PP
Definition at line 21 of file graphics.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
