.TH "/home/jefbed/src/arwm/key_event.c" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/key_event.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'arwm.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBspawn_terminal\fP()   arwm_system(opt.term)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBarwm_handle_key_event\fP (XKeyEvent *e)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define spawn_terminal()   arwm_system(opt.term)"
.PP
Definition at line 112 of file key_event.c.
.SH "Function Documentation"
.PP 
.SS "void arwm_handle_key_event (XKeyEvent *e)"
.PP
Definition at line 115 of file key_event.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
