.TH "/home/jefbed/src/arwm/keymap.h" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/keymap.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBKEY_NEXT\fP   XK_Tab"
.br
.ti -1c
.RI "#define \fBKEY_NEW\fP   XK_Return"
.br
.ti -1c
.RI "#define \fBKEY_LOCK\fP   XK_F1"
.br
.ti -1c
.RI "#define \fBKEY_SLEEP\fP   XK_F3"
.br
.ti -1c
.RI "#define \fBKEY_QUIT\fP   XK_Escape"
.br
.ti -1c
.RI "#define \fBKEY_TOPLEFT\fP   XK_KP_Home"
.br
.ti -1c
.RI "#define \fBKEY_TOPRIGHT\fP   XK_KP_Page_Up"
.br
.ti -1c
.RI "#define \fBKEY_BOTTOMLEFT\fP   XK_KP_End"
.br
.ti -1c
.RI "#define \fBKEY_BOTTOMRIGHT\fP   XK_KP_Page_Down"
.br
.ti -1c
.RI "#define \fBKEY_RAISE\fP   XK_KP_Up"
.br
.ti -1c
.RI "#define \fBKEY_LOWER\fP   XK_KP_Down"
.br
.ti -1c
.RI "#define \fBKEY_PREVDESK\fP   XK_grave"
.br
.ti -1c
.RI "#define \fBKEY_NEXTDESK\fP   XK_minus"
.br
.ti -1c
.RI "#define \fBKEY_UP\fP   XK_k"
.br
.ti -1c
.RI "#define \fBKEY_DOWN\fP   XK_j"
.br
.ti -1c
.RI "#define \fBKEY_LEFT\fP   XK_h"
.br
.ti -1c
.RI "#define \fBKEY_RIGHT\fP   XK_l"
.br
.ti -1c
.RI "#define \fBKEY_ALTLOWER\fP   XK_KP_Insert"
.br
.ti -1c
.RI "#define \fBKEY_INFO\fP   XK_F5"
.br
.ti -1c
.RI "#define \fBKEY_MAX\fP   XK_space"
.br
.ti -1c
.RI "#define \fBKEY_FIX\fP   XK_KP_5"
.br
.ti -1c
.RI "#define \fBKEY_MOVE\fP   XK_Super_L"
.br
.ti -1c
.RI "#define \fBKEY_KILL\fP   XK_F4"
.br
.ti -1c
.RI "#define \fBARWM_VWM_KEYS\fP"
.br
.ti -1c
.RI "#define \fBARWM_KEYS_TO_GRAB\fP"
.br
.ti -1c
.RI "#define \fBARWM_ALT_KEYS_TO_GRAB\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgrab_keys_for_screen\fP (\fBScreenInfo\fP *s)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ARWM_ALT_KEYS_TO_GRAB"\fBValue:\fP
.PP
.nf
{\
        KEY_KILL, KEY_LEFT, KEY_RIGHT, KEY_DOWN, KEY_UP, 0\
};
.fi
.PP
Definition at line 65 of file keymap.h.
.SS "#define ARWM_KEYS_TO_GRAB"\fBValue:\fP
.PP
.nf
{\
        KEY_NEXT, KEY_NEW, KEY_LOCK, KEY_QUIT, KEY_KILL,\
        KEY_TOPLEFT, KEY_TOPRIGHT, KEY_BOTTOMLEFT, KEY_BOTTOMRIGHT,\
        KEY_LEFT, KEY_RIGHT, KEY_DOWN, KEY_UP,\
        KEY_LOWER, KEY_ALTLOWER, KEY_INFO, KEY_MAX,\
        ARWM_VWM_KEYS, KEY_MOVE, KEY_RAISE, 0\
};
.fi
.PP
Definition at line 56 of file keymap.h.
.SS "#define ARWM_VWM_KEYS"\fBValue:\fP
.PP
.nf
KEY_FIX, KEY_PREVDESK, KEY_NEXTDESK,\
                XK_1, XK_2, XK_3, XK_4, XK_5, XK_6, XK_7, XK_8, XK_9
.fi
.PP
Definition at line 52 of file keymap.h.
.SS "#define KEY_ALTLOWER   XK_KP_Insert"
.PP
Definition at line 39 of file keymap.h.
.SS "#define KEY_BOTTOMLEFT   XK_KP_End"
.PP
Definition at line 15 of file keymap.h.
.SS "#define KEY_BOTTOMRIGHT   XK_KP_Page_Down"
.PP
Definition at line 16 of file keymap.h.
.SS "#define KEY_DOWN   XK_j"
.PP
Definition at line 34 of file keymap.h.
.SS "#define KEY_FIX   XK_KP_5"
.PP
Definition at line 42 of file keymap.h.
.SS "#define KEY_INFO   XK_F5"
.PP
Definition at line 40 of file keymap.h.
.SS "#define KEY_KILL   XK_F4"
.PP
Definition at line 49 of file keymap.h.
.SS "#define KEY_LEFT   XK_h"
.PP
Definition at line 35 of file keymap.h.
.SS "#define KEY_LOCK   XK_F1"
.PP
Definition at line 10 of file keymap.h.
.SS "#define KEY_LOWER   XK_KP_Down"
.PP
Definition at line 19 of file keymap.h.
.SS "#define KEY_MAX   XK_space"
.PP
Definition at line 41 of file keymap.h.
.SS "#define KEY_MOVE   XK_Super_L"
.PP
Definition at line 43 of file keymap.h.
.SS "#define KEY_NEW   XK_Return"
.PP
Definition at line 8 of file keymap.h.
.SS "#define KEY_NEXT   XK_Tab"
.PP
Definition at line 6 of file keymap.h.
.SS "#define KEY_NEXTDESK   XK_minus"
.PP
Definition at line 25 of file keymap.h.
.SS "#define KEY_PREVDESK   XK_grave"
.PP
Definition at line 24 of file keymap.h.
.SS "#define KEY_QUIT   XK_Escape"
.PP
Definition at line 12 of file keymap.h.
.SS "#define KEY_RAISE   XK_KP_Up"
.PP
Definition at line 18 of file keymap.h.
.SS "#define KEY_RIGHT   XK_l"
.PP
Definition at line 36 of file keymap.h.
.SS "#define KEY_SLEEP   XK_F3"
.PP
Definition at line 11 of file keymap.h.
.SS "#define KEY_TOPLEFT   XK_KP_Home"
.PP
Definition at line 13 of file keymap.h.
.SS "#define KEY_TOPRIGHT   XK_KP_Page_Up"
.PP
Definition at line 14 of file keymap.h.
.SS "#define KEY_UP   XK_k"
.PP
Definition at line 33 of file keymap.h.
.SH "Function Documentation"
.PP 
.SS "void grab_keys_for_screen (\fBScreenInfo\fP *s)"
.PP
Definition at line 53 of file keymap.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
