.TH "/home/jefbed/src/arwm/keymap.c" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/keymap.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'arwm.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgrab_keys_for_screen\fP (\fBScreenInfo\fP *s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void grab_keys_for_screen (\fBScreenInfo\fP *s)"
.PP
Definition at line 53 of file keymap.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
