.TH "log.h" 3 "Sun Jan 8 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLOG_INFO\fP(...)   printf(__VA_ARGS__);"
.br
.ti -1c
.RI "#define \fBLOG_ERROR\fP(...)   fprintf(stderr, __VA_ARGS__);"
.br
.ti -1c
.RI "#define \fBLOG_DEBUG\fP(...)"
.br
.ti -1c
.RI "#define \fBMARK\fP"
.br
.ti -1c
.RI "#define \fBLOG_XDEBUG\fP(...)"
.br
.ti -1c
.RI "#define \fBLOG_EDEBUG\fP(...)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define LOG_DEBUG(...)"
.PP
Definition at line 22 of file log.h.
.SS "#define LOG_EDEBUG(...)"
.PP
Definition at line 35 of file log.h.
.SS "#define LOG_ERROR(...)   fprintf(stderr, __VA_ARGS__);"
.PP
Definition at line 12 of file log.h.
.SS "#define LOG_INFO(...)   printf(__VA_ARGS__);"
.PP
Definition at line 11 of file log.h.
.SS "#define LOG_XDEBUG(...)"
.PP
Definition at line 29 of file log.h.
.SS "#define MARK"
.PP
Definition at line 23 of file log.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
