.TH "/home/jefbed/src/arwm/macros.h" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/macros.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'flags.h'\fP
.br
\fC#include <stdio.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAX\fP(x, y)   (((x)>(y)) ? (x) : (y))"
.br
.ti -1c
.RI "#define \fBLOG\fP(msg)"
.br
.ti -1c
.RI "#define \fBLOG_ERROR\fP(msg)   {fputs(msg, stderr); exit(1);}"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define LOG(msg)"
.PP
Definition at line 17 of file macros.h.
.SS "#define LOG_ERROR(msg)   {fputs(msg, stderr); exit(1);}"
.PP
Definition at line 20 of file macros.h.
.SS "#define MAX(x, y)   (((x)>(y)) ? (x) : (y))"
.PP
Definition at line 9 of file macros.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
