.TH "/home/jefbed/src/arwm/misc.h" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/misc.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__attribute__\fP ((noreturn)) void arwm_exit(const int status)"
.br
.ti -1c
.RI "int \fBhandle_xerror\fP (Display *dpy, XErrorEvent *e)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "__attribute__ ((noreturn)) const"
.SS "int handle_xerror (Display *dpy, XErrorEvent *e)"
.PP
Definition at line 47 of file misc.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
