.TH "/home/jefbed/src/arwm/misc.c" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/misc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <X11/Xproto.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <stdarg.h>\fP
.br
\fC#include <signal.h>\fP
.br
\fC#include <sys/wait.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include 'arwm.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__attribute__\fP ((noreturn))"
.br
.ti -1c
.RI "int \fBhandle_xerror\fP (Display *dpy, XErrorEvent *e)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "__attribute__ ((noreturn))"
.PP
Definition at line 14 of file misc.c.
.SS "int handle_xerror (Display *dpy, XErrorEvent *e)"
.PP
Definition at line 47 of file misc.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
