.TH "/home/jefbed/src/arwm/new.h" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/new.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBarwm_get_property\fP (Window w, Atom property, Atom req_type, unsigned long *nitems_return)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* arwm_get_property (Windoww, Atomproperty, Atomreq_type, unsigned long *nitems_return)"
.PP
Definition at line 434 of file new.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
