.TH "Position" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Position \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <screen.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "short \fBx\fP"
.br
.ti -1c
.RI "short \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file screen.h.
.SH "Field Documentation"
.PP 
.SS "short \fBx\fP"
.PP
Definition at line 7 of file screen.h.
.SS "short \fBy\fP"
.PP
Definition at line 7 of file screen.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
