.TH "PropMwmHints" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PropMwmHints \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arwm.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long \fBflags\fP"
.br
.ti -1c
.RI "unsigned long \fBfunctions\fP"
.br
.ti -1c
.RI "unsigned long \fBdecorations\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file arwm.h.
.SH "Field Documentation"
.PP 
.SS "unsigned long \fBdecorations\fP"
.PP
Definition at line 35 of file arwm.h.
.SS "unsigned long \fBflags\fP"
.PP
Definition at line 33 of file arwm.h.
.SS "unsigned long \fBfunctions\fP"
.PP
Definition at line 34 of file arwm.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
