.TH "/home/jefbed/src/arwm/ScreenInfo.h" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/ScreenInfo.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBScreenInfo\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBScreenInfo\fP \fBScreenInfo\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBScreenInfo\fP  \fBScreenInfo\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
