.TH "ScreenInfo" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScreenInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScreenInfo.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBscreen\fP"
.br
.ti -1c
.RI "Window \fBroot\fP"
.br
.ti -1c
.RI "GC \fBgc\fP"
.br
.ti -1c
.RI "XColor \fBfg\fP"
.br
.ti -1c
.RI "XColor \fBbg\fP"
.br
.ti -1c
.RI "\fBubyte\fP \fBvdesk\fP"
.br
.ti -1c
.RI "XColor \fBfc\fP"
.br
.ti -1c
.RI "char * \fBdisplay\fP"
.br
.ti -1c
.RI "unsigned short \fBwidth\fP"
.br
.ti -1c
.RI "unsigned short \fBheight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file ScreenInfo.h.
.SH "Field Documentation"
.PP 
.SS "XColor \fBbg\fP"
.PP
Definition at line 9 of file ScreenInfo.h.
.SS "char* \fBdisplay\fP"
.PP
Definition at line 12 of file ScreenInfo.h.
.SS "XColor \fBfc\fP"
.PP
Definition at line 11 of file ScreenInfo.h.
.SS "XColor \fBfg\fP"
.PP
Definition at line 9 of file ScreenInfo.h.
.SS "GC \fBgc\fP"
.PP
Definition at line 8 of file ScreenInfo.h.
.SS "unsigned short \fBheight\fP"
.PP
Definition at line 13 of file ScreenInfo.h.
.SS "Window \fBroot\fP"
.PP
Definition at line 7 of file ScreenInfo.h.
.SS "int \fBscreen\fP"
.PP
Definition at line 6 of file ScreenInfo.h.
.SS "\fBubyte\fP \fBvdesk\fP"
.PP
Definition at line 10 of file ScreenInfo.h.
.SS "unsigned short \fBwidth\fP"
.PP
Definition at line 13 of file ScreenInfo.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
