.TH "/home/jefbed/src/arwm/screen.c" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/screen.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'arwm.h'\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'screen.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBsetwh\fP(wh, mm, gtlt)"
.br
.ti -1c
.RI "#define \fBgrab_pointer\fP(w, mask, curs)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsweep\fP (\fBClient\fP *c)"
.br
.ti -1c
.RI "void \fBdrag\fP (\fBClient\fP *c)"
.br
.ti -1c
.RI "void \fBmoveresize\fP (\fBClient\fP *c)"
.br
.ti -1c
.RI "void \fBmaximize\fP (\fBClient\fP *c)"
.br
.ti -1c
.RI "void \fBhide\fP (\fBClient\fP *c)"
.br
.ti -1c
.RI "void \fBunhide\fP (\fBClient\fP *c, int raise_win)"
.br
.ti -1c
.RI "void \fBnext\fP (void)"
.br
.ti -1c
.RI "void \fBswitch_vdesk\fP (\fBScreenInfo\fP *s, const \fBubyte\fP v)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define grab_pointer(w, mask, curs)"\fBValue:\fP
.PP
.nf
(XGrabPointer(arwm.X.dpy, w, False, mask, GrabModeAsync,\
        GrabModeAsync, None, curs, CurrentTime) == GrabSuccess)
.fi
.PP
Definition at line 85 of file screen.c.
.SS "#define setwh(wh, mm, gtlt)"\fBValue:\fP
.PP
.nf
if(c->mm##_##wh && g->wh gtlt c->mm##_##wh)\
        g->wh = c->mm##_##wh;
.fi
.SH "Function Documentation"
.PP 
.SS "void drag (\fBClient\fP *c)"
.PP
Definition at line 241 of file screen.c.
.SS "void hide (\fBClient\fP *c)"
.PP
Definition at line 308 of file screen.c.
.SS "void maximize (\fBClient\fP *c)"
.PP
Definition at line 281 of file screen.c.
.SS "void moveresize (\fBClient\fP *c)"
.PP
Definition at line 256 of file screen.c.
.SS "void next (void)"
.PP
Definition at line 326 of file screen.c.
.SS "void sweep (\fBClient\fP *c)"
.PP
Definition at line 104 of file screen.c.
.SS "void switch_vdesk (\fBScreenInfo\fP *s, const \fBubyte\fPv)"
.PP
Definition at line 357 of file screen.c.
.SS "void unhide (\fBClient\fP *c, intraise_win)"
.PP
Definition at line 318 of file screen.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
