.TH "/home/jefbed/src/arwm/titlebar.h" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/titlebar.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'graphics.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_ARWMTitlebarData\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBAR_BUTTON_WIDTH\fP   TITLEBAR_HEIGHT"
.br
.ti -1c
.RI "#define \fBAR_BUTTON_HEIGHT\fP   TITLEBAR_HEIGHT"
.br
.ti -1c
.RI "#define \fBAR_RESIZE_BUTTON_WIDTH\fP   AR_BUTTON_WIDTH"
.br
.ti -1c
.RI "#define \fBAR_RESIZE_DELTA\fP   (AR_RESIZE_BUTTON_WIDTH+ARWM_BORDER_WIDTH)"
.br
.ti -1c
.RI "#define \fBAR_SHADE_DELTA\fP   (AR_RESIZE_DELTA+AR_BUTTON_WIDTH+ARWM_BORDER_WIDTH)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_ARWMTitlebarData\fP \fBARWMTitlebarData\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBARWMTitlebarData_delete\fP (\fBARWMTitlebarData\fP *titlebar)"
.br
.ti -1c
.RI "void \fBarwm_ARWMTitlebarData_init\fP (\fBARWMTitlebarData\fP *titlebar)"
.br
.ti -1c
.RI "void \fBupdate_info_window\fP (\fBClient\fP *c)"
.br
.ti -1c
.RI "void \fBremove_info_window\fP (\fBClient\fP *c)"
.br
.ti -1c
.RI "void \fBarwm_draw_close_button\fP (\fBClient\fP *c)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define AR_BUTTON_HEIGHT   TITLEBAR_HEIGHT"
.PP
Definition at line 43 of file titlebar.h.
.SS "#define AR_BUTTON_WIDTH   TITLEBAR_HEIGHT"
.PP
Definition at line 42 of file titlebar.h.
.SS "#define AR_RESIZE_BUTTON_WIDTH   AR_BUTTON_WIDTH"
.PP
Definition at line 47 of file titlebar.h.
.SS "#define AR_RESIZE_DELTA   (AR_RESIZE_BUTTON_WIDTH+ARWM_BORDER_WIDTH)"
.PP
Definition at line 49 of file titlebar.h.
.SS "#define AR_SHADE_DELTA   (AR_RESIZE_DELTA+AR_BUTTON_WIDTH+ARWM_BORDER_WIDTH)"
.PP
Definition at line 50 of file titlebar.h.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_ARWMTitlebarData\fP  \fBARWMTitlebarData\fP"
.SH "Function Documentation"
.PP 
.SS "void arwm_ARWMTitlebarData_init (\fBARWMTitlebarData\fP *titlebar)"
.PP
Definition at line 213 of file titlebar.c.
.SS "void arwm_draw_close_button (\fBClient\fP *c)"
.SS "void ARWMTitlebarData_delete (\fBARWMTitlebarData\fP *titlebar)"
.PP
Definition at line 268 of file titlebar.c.
.SS "void remove_info_window (\fBClient\fP *c)"
.PP
Definition at line 311 of file titlebar.c.
.SS "void update_info_window (\fBClient\fP *c)"
.PP
Definition at line 282 of file titlebar.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
