.TH "/home/jefbed/src/arwm/titlebar.c" 3 "Wed Mar 7 2012" "arwm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jefbed/src/arwm/titlebar.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'arwm.h'\fP
.br
\fC#include 'ARWMButton.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBarwm_draw_close_button\fP(c)"
.br
.ti -1c
.RI "#define \fBIMG\fP(item)   NULL"
.br
.ti -1c
.RI "#define \fBIMGDIM\fP(item)"
.br
.ti -1c
.RI "#define \fBTBUTTON\fP(item, bg)"
.br
.ti -1c
.RI "#define \fBRGB_TBUTTON\fP(item, bg)   TBUTTON(item, arwm_new_gc(bg))"
.br
.ti -1c
.RI "#define \fBXCOLOR_TBUTTON\fP(item, bg)   TBUTTON(item, arwm_new_gc_for_XColor(bg))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBarwm_ARWMTitlebarData_init\fP (\fBARWMTitlebarData\fP *titlebar)"
.br
.ti -1c
.RI "void \fBARWMTitlebarData_delete\fP (\fBARWMTitlebarData\fP *titlebar)"
.br
.ti -1c
.RI "void \fBupdate_info_window\fP (\fBClient\fP *c)"
.br
.ti -1c
.RI "void \fBremove_info_window\fP (\fBClient\fP *c)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define arwm_draw_close_button(c)"\fBValue:\fP
.PP
.nf
draw_button(arwm.titlebar.buttons.close,\
                c->info_window, 0);
.fi
.PP
Definition at line 102 of file titlebar.c.
.SS "#define IMG(item)   NULL"
.SS "#define IMGDIM(item)"
.SS "#define RGB_TBUTTON(item, bg)   TBUTTON(item, arwm_new_gc(bg))"
.SS "#define TBUTTON(item, bg)"\fBValue:\fP
.PP
.nf
item = titlebar->buttons.item = ARWMButton_new(\
        root, bg, TITLEBAR_HEIGHT,\
        TITLEBAR_HEIGHT, IMG(item)); IMGDIM(item)
.fi
.SS "#define XCOLOR_TBUTTON(item, bg)   TBUTTON(item, arwm_new_gc_for_XColor(bg))"
.SH "Function Documentation"
.PP 
.SS "void arwm_ARWMTitlebarData_init (\fBARWMTitlebarData\fP *titlebar)"
.PP
Definition at line 213 of file titlebar.c.
.SS "void ARWMTitlebarData_delete (\fBARWMTitlebarData\fP *titlebar)"
.PP
Definition at line 268 of file titlebar.c.
.SS "void remove_info_window (\fBClient\fP *c)"
.PP
Definition at line 311 of file titlebar.c.
.SS "void update_info_window (\fBClient\fP *c)"
.PP
Definition at line 282 of file titlebar.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for arwm from the source code.
